# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.1.1
_src_path: https://github.com/wabenet/copier-dodo-plugin
author_email: ole.claussen@wabenet.com
author_name: Ole Claussen
description: Adds support for buildkit as a dodo builder plugin.
go_version: '1.18'
is_standalone: true
lifecycle: production
name: buildkit
use_protobuf: false

