---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dodo-buildkit
  description: Adds support for buildkit as a dodo builder plugin.

spec:
  type: library
  lifecycle: production
  owner: ole.claussen@wabenet.com
