// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/types/types.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Backdrop struct {
	Name                 string     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Aliases              []string   `protobuf:"bytes,2,rep,name=aliases,proto3" json:"aliases,omitempty"`
	Build                *BuildInfo `protobuf:"bytes,3,opt,name=build,proto3" json:"build,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Backdrop) Reset()         { *m = Backdrop{} }
func (m *Backdrop) String() string { return proto.CompactTextString(m) }
func (*Backdrop) ProtoMessage()    {}
func (*Backdrop) Descriptor() ([]byte, []int) {
	return fileDescriptor_6579d14f41ea6320, []int{0}
}

func (m *Backdrop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Backdrop.Unmarshal(m, b)
}
func (m *Backdrop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Backdrop.Marshal(b, m, deterministic)
}
func (m *Backdrop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Backdrop.Merge(m, src)
}
func (m *Backdrop) XXX_Size() int {
	return xxx_messageInfo_Backdrop.Size(m)
}
func (m *Backdrop) XXX_DiscardUnknown() {
	xxx_messageInfo_Backdrop.DiscardUnknown(m)
}

var xxx_messageInfo_Backdrop proto.InternalMessageInfo

func (m *Backdrop) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Backdrop) GetAliases() []string {
	if m != nil {
		return m.Aliases
	}
	return nil
}

func (m *Backdrop) GetBuild() *BuildInfo {
	if m != nil {
		return m.Build
	}
	return nil
}

type BuildInfo struct {
	ImageName            string      `protobuf:"bytes,1,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	Context              string      `protobuf:"bytes,2,opt,name=context,proto3" json:"context,omitempty"`
	Dockerfile           string      `protobuf:"bytes,3,opt,name=dockerfile,proto3" json:"dockerfile,omitempty"`
	InlineDockerfile     []string    `protobuf:"bytes,4,rep,name=inline_dockerfile,json=inlineDockerfile,proto3" json:"inline_dockerfile,omitempty"`
	Arguments            []*Argument `protobuf:"bytes,5,rep,name=arguments,proto3" json:"arguments,omitempty"`
	Secrets              []*Secret   `protobuf:"bytes,6,rep,name=secrets,proto3" json:"secrets,omitempty"`
	SshAgents            []*SshAgent `protobuf:"bytes,7,rep,name=ssh_agents,json=sshAgents,proto3" json:"ssh_agents,omitempty"`
	NoCache              bool        `protobuf:"varint,8,opt,name=no_cache,json=noCache,proto3" json:"no_cache,omitempty"`
	ForceRebuild         bool        `protobuf:"varint,9,opt,name=force_rebuild,json=forceRebuild,proto3" json:"force_rebuild,omitempty"`
	ForcePull            bool        `protobuf:"varint,10,opt,name=force_pull,json=forcePull,proto3" json:"force_pull,omitempty"`
	Dependencies         []string    `protobuf:"bytes,11,rep,name=dependencies,proto3" json:"dependencies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BuildInfo) Reset()         { *m = BuildInfo{} }
func (m *BuildInfo) String() string { return proto.CompactTextString(m) }
func (*BuildInfo) ProtoMessage()    {}
func (*BuildInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6579d14f41ea6320, []int{1}
}

func (m *BuildInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildInfo.Unmarshal(m, b)
}
func (m *BuildInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildInfo.Marshal(b, m, deterministic)
}
func (m *BuildInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildInfo.Merge(m, src)
}
func (m *BuildInfo) XXX_Size() int {
	return xxx_messageInfo_BuildInfo.Size(m)
}
func (m *BuildInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildInfo.DiscardUnknown(m)
}

var xxx_messageInfo_BuildInfo proto.InternalMessageInfo

func (m *BuildInfo) GetImageName() string {
	if m != nil {
		return m.ImageName
	}
	return ""
}

func (m *BuildInfo) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *BuildInfo) GetDockerfile() string {
	if m != nil {
		return m.Dockerfile
	}
	return ""
}

func (m *BuildInfo) GetInlineDockerfile() []string {
	if m != nil {
		return m.InlineDockerfile
	}
	return nil
}

func (m *BuildInfo) GetArguments() []*Argument {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func (m *BuildInfo) GetSecrets() []*Secret {
	if m != nil {
		return m.Secrets
	}
	return nil
}

func (m *BuildInfo) GetSshAgents() []*SshAgent {
	if m != nil {
		return m.SshAgents
	}
	return nil
}

func (m *BuildInfo) GetNoCache() bool {
	if m != nil {
		return m.NoCache
	}
	return false
}

func (m *BuildInfo) GetForceRebuild() bool {
	if m != nil {
		return m.ForceRebuild
	}
	return false
}

func (m *BuildInfo) GetForcePull() bool {
	if m != nil {
		return m.ForcePull
	}
	return false
}

func (m *BuildInfo) GetDependencies() []string {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

type Argument struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Argument) Reset()         { *m = Argument{} }
func (m *Argument) String() string { return proto.CompactTextString(m) }
func (*Argument) ProtoMessage()    {}
func (*Argument) Descriptor() ([]byte, []int) {
	return fileDescriptor_6579d14f41ea6320, []int{2}
}

func (m *Argument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Argument.Unmarshal(m, b)
}
func (m *Argument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Argument.Marshal(b, m, deterministic)
}
func (m *Argument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Argument.Merge(m, src)
}
func (m *Argument) XXX_Size() int {
	return xxx_messageInfo_Argument.Size(m)
}
func (m *Argument) XXX_DiscardUnknown() {
	xxx_messageInfo_Argument.DiscardUnknown(m)
}

var xxx_messageInfo_Argument proto.InternalMessageInfo

func (m *Argument) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Argument) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Secret struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Secret) Reset()         { *m = Secret{} }
func (m *Secret) String() string { return proto.CompactTextString(m) }
func (*Secret) ProtoMessage()    {}
func (*Secret) Descriptor() ([]byte, []int) {
	return fileDescriptor_6579d14f41ea6320, []int{3}
}

func (m *Secret) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Secret.Unmarshal(m, b)
}
func (m *Secret) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Secret.Marshal(b, m, deterministic)
}
func (m *Secret) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Secret.Merge(m, src)
}
func (m *Secret) XXX_Size() int {
	return xxx_messageInfo_Secret.Size(m)
}
func (m *Secret) XXX_DiscardUnknown() {
	xxx_messageInfo_Secret.DiscardUnknown(m)
}

var xxx_messageInfo_Secret proto.InternalMessageInfo

func (m *Secret) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Secret) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type SshAgent struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IdentityFile         string   `protobuf:"bytes,2,opt,name=identity_file,json=identityFile,proto3" json:"identity_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SshAgent) Reset()         { *m = SshAgent{} }
func (m *SshAgent) String() string { return proto.CompactTextString(m) }
func (*SshAgent) ProtoMessage()    {}
func (*SshAgent) Descriptor() ([]byte, []int) {
	return fileDescriptor_6579d14f41ea6320, []int{4}
}

func (m *SshAgent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SshAgent.Unmarshal(m, b)
}
func (m *SshAgent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SshAgent.Marshal(b, m, deterministic)
}
func (m *SshAgent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SshAgent.Merge(m, src)
}
func (m *SshAgent) XXX_Size() int {
	return xxx_messageInfo_SshAgent.Size(m)
}
func (m *SshAgent) XXX_DiscardUnknown() {
	xxx_messageInfo_SshAgent.DiscardUnknown(m)
}

var xxx_messageInfo_SshAgent proto.InternalMessageInfo

func (m *SshAgent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SshAgent) GetIdentityFile() string {
	if m != nil {
		return m.IdentityFile
	}
	return ""
}

func init() {
	proto.RegisterType((*Backdrop)(nil), "types.Backdrop")
	proto.RegisterType((*BuildInfo)(nil), "types.BuildInfo")
	proto.RegisterType((*Argument)(nil), "types.Argument")
	proto.RegisterType((*Secret)(nil), "types.Secret")
	proto.RegisterType((*SshAgent)(nil), "types.SshAgent")
}

func init() { proto.RegisterFile("pkg/types/types.proto", fileDescriptor_6579d14f41ea6320) }

var fileDescriptor_6579d14f41ea6320 = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0x61, 0x8f, 0xd3, 0x3c,
	0x0c, 0xc7, 0xb5, 0xf5, 0xb6, 0xb5, 0xde, 0xf6, 0x3c, 0x23, 0x02, 0x29, 0xbc, 0x00, 0x55, 0x3d,
	0x09, 0x2a, 0x01, 0x43, 0x1a, 0x1f, 0x00, 0xdd, 0x81, 0x90, 0x78, 0x83, 0x50, 0xef, 0x03, 0x94,
	0x5c, 0xeb, 0x75, 0xd1, 0xb2, 0xa4, 0x6a, 0x52, 0xc4, 0xbe, 0x0b, 0x1f, 0x16, 0xd5, 0x49, 0xb9,
	0x9d, 0x78, 0x13, 0xd9, 0x3f, 0xff, 0x63, 0xc7, 0x76, 0xe0, 0x59, 0x7b, 0x6c, 0xde, 0xbb, 0x73,
	0x8b, 0xd6, 0x9f, 0xdb, 0xb6, 0x33, 0xce, 0xb0, 0x19, 0x39, 0xd9, 0x0f, 0x88, 0x6f, 0x45, 0x75,
	0xac, 0x3b, 0xd3, 0x32, 0x06, 0x57, 0x5a, 0x9c, 0x90, 0x4f, 0xd2, 0x49, 0x9e, 0x14, 0x64, 0x33,
	0x0e, 0x0b, 0xa1, 0xa4, 0xb0, 0x68, 0xf9, 0x34, 0x8d, 0xf2, 0xa4, 0x18, 0x5d, 0xf6, 0x0a, 0x66,
	0xf7, 0xbd, 0x54, 0x35, 0x8f, 0xd2, 0x49, 0xbe, 0xdc, 0x6d, 0xb6, 0x3e, 0xfb, 0xed, 0xc0, 0xbe,
	0xea, 0xbd, 0x29, 0x7c, 0x38, 0xfb, 0x1d, 0x41, 0xf2, 0x17, 0xb2, 0x17, 0x00, 0xf2, 0x24, 0x1a,
	0x2c, 0x2f, 0x2a, 0x25, 0x44, 0xbe, 0x85, 0x72, 0x95, 0xd1, 0x0e, 0x7f, 0x39, 0x3e, 0xa5, 0xd8,
	0xe8, 0xb2, 0x97, 0x00, 0xb5, 0xa9, 0x8e, 0xd8, 0xed, 0xa5, 0x42, 0xaa, 0x99, 0x14, 0x17, 0x84,
	0xbd, 0x81, 0x27, 0x52, 0x2b, 0xa9, 0xb1, 0xbc, 0x90, 0x5d, 0xd1, 0x93, 0x37, 0x3e, 0xf0, 0xf9,
	0x41, 0xfc, 0x0e, 0x12, 0xd1, 0x35, 0xfd, 0x09, 0xb5, 0xb3, 0x7c, 0x96, 0x46, 0xf9, 0x72, 0xf7,
	0x7f, 0x78, 0xff, 0x4d, 0xe0, 0xc5, 0x83, 0x82, 0xbd, 0x86, 0x85, 0xc5, 0xaa, 0x43, 0x67, 0xf9,
	0x9c, 0xc4, 0xeb, 0x20, 0xbe, 0x23, 0x5a, 0x8c, 0x51, 0xb6, 0x05, 0xb0, 0xf6, 0x50, 0x8a, 0x86,
	0x12, 0x2f, 0x1e, 0x25, 0xbe, 0xb3, 0x87, 0x9b, 0x86, 0x12, 0xdb, 0x60, 0x59, 0xf6, 0x1c, 0x62,
	0x6d, 0xca, 0x4a, 0x54, 0x07, 0xe4, 0x71, 0x3a, 0xc9, 0xe3, 0x62, 0xa1, 0xcd, 0xa7, 0xc1, 0x65,
	0xd7, 0xb0, 0xde, 0x9b, 0xae, 0xc2, 0xb2, 0x43, 0x3f, 0xe6, 0x84, 0xe2, 0x2b, 0x82, 0x85, 0x67,
	0xc3, 0x34, 0xbd, 0xa8, 0xed, 0x95, 0xe2, 0x40, 0x8a, 0x84, 0xc8, 0xf7, 0x5e, 0x29, 0x96, 0xc1,
	0xaa, 0xc6, 0x16, 0x75, 0x8d, 0xba, 0x92, 0x68, 0xf9, 0x92, 0xc6, 0xf1, 0x88, 0x65, 0x3b, 0x88,
	0xc7, 0x96, 0xd9, 0x06, 0xa2, 0x23, 0x9e, 0xc3, 0x56, 0x06, 0x93, 0x3d, 0x85, 0xd9, 0x4f, 0xa1,
	0x7a, 0x0c, 0xdb, 0xf0, 0x4e, 0xf6, 0x16, 0xe6, 0xbe, 0x73, 0xf6, 0x1f, 0x4c, 0x65, 0x1d, 0x2e,
	0x4c, 0x65, 0x3d, 0x7c, 0xa1, 0x56, 0xb8, 0x43, 0x90, 0x93, 0x9d, 0x7d, 0x84, 0x78, 0xec, 0xfd,
	0x1f, 0xfd, 0x35, 0xac, 0x65, 0x8d, 0xda, 0x49, 0x77, 0x2e, 0x69, 0x63, 0xfe, 0xe2, 0x6a, 0x84,
	0x5f, 0xa4, 0xc2, 0xfb, 0x39, 0xfd, 0xd8, 0x0f, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x43, 0x7a,
	0x79, 0x24, 0xca, 0x02, 0x00, 0x00,
}
